version: "3"
services:
    django_site:
        build: 
            context: .
        volumes: 
            - .:/code
        restart: always
        expose: 
            - 8001   
        command: >
            sh -c "uwsgi --ini ./config/uwsgi.ini"
    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        ports: 
            - "8000:8000"
        

